accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

either/urls.py
from django.contrib import admin
from django.urls import path, include
from questions import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index),
]

questions/urls.py
from django.urls import path, include
from . import views

app_name = "questions"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:id>/', views.detail, name="detail"),
    path('<int:id>/update', views.update, name="update"),
    path('<int:id>/delete', views.delete, name="delete"),
    path('<int:id>/choices/create/', views.choice_create, name="choice_create"),
    path('<int:question_id>/choices/<int:choice_id>/delete/',
         views.choice_delete, name="choice_delete")
]

accounts/models.py
from django.db import models

# Create your models here.

questions/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=100)
    choice_1 = models.CharField(max_length=100)
    choice_2 = models.CharField(max_length=100)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.IntegerField()
    comment = models.CharField(max_length=100)

questions/forms.py
from django import forms
from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'


class ChoiceForm(forms.ModelForm):
    choices = [(1, '왼쪽'), (2, '오른쪽')]
    pick = forms.ChoiceField(choices=choices, widget=forms.RadioSelect)

    class Meta:
        model = Choice
        fields = ('pick', 'comment',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('questions:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('questions:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('questions:index')

questions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import QuestionForm, ChoiceForm
from .models import Question, Choice
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    questions = Question.objects.all()
    return render(request, 'questions/index.html', {'questions': questions})


def detail(request, id):
    question = get_object_or_404(Question, id=id)
    choice_form = ChoiceForm()

    choices = question.choice_set.all()

    total_1 = choices.filter(pick=1).count()
    total_2 = choices.filter(pick=2).count()

    total_sum = total_1 + total_2

    percent_1 = total_1 / total_sum * 100

    if total_sum == 0:
        percent_1 = 0
        percent_2 = 0

    else:
        percent_1 = total_1 / total_sum * 100
        percent_2 = total_2 / total_sum * 100

    context = {
        'question': question,
        'choice_form': choice_form,
        'percent_1': percent_1,
        'percent_2': percent_2,
    }
    return render(request, 'questions/detail.html', context)


@login_required
def create(request):
    # 1. 사용자가 데이터를 입력하기 위해서 GET요청(폼을 요청)
    # 6. 사용자가 올바르지 않은 데이터를 입력하고, POST 요청
    # 12. 사용자가 올바른 데이터를 입력하고, POST 요청

    # 7. POST method로 들어오기 때문에 if문 실행
    # 13. POST method로 들어오기 때문에 if문 실행
    if request.method == "POST":
        # 8. 사용자의 데이터를 모델폼에 입력
        # 14. 사용자의 데이터를 모델폼에 입력
        form = QuestionForm(request.POST)
        # 9. 데이터가 올바른지 검증
        # 15. 데이터가 올바른지 검증
        if form.is_valid():
            # 16. 데이터가 검증을 통과하고 저장
            form.save()
            # 17. 저장 후 메인으로 이동
            return redirect('questions:index')
    # 2. GET method로 들어오기 때문에 else문 실행
    else:
        # 3. 사용자에게 빈 폼을 보여주기 위해서
        # 모델폼을 인스턴스화 한 후  form 변수에 저장
        form = QuestionForm()
    # 4. dict로 만들기
    # 10. 검증을 통과 못했을 경우
    #     => 올바른 데이터는 남기고 다시 폼 보여주기
    context = {
        'form': form
    }
    # 5. form.html 보여주기
    # 11. form.html 보여주기
    return render(request, 'questions/form.html', context)


def update(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect('questions:detail', id)
    else:
        form = QuestionForm(instance=question)

    context = {
        'form': form
    }
    return render(request, 'questions/form.html', context)


def delete(request, id):
    if request.method == "POST":
        question = get_object_or_404(Question, id=id)
        question.delete()
        return redirect('questions:index')
    else:
        return redirect('questions:detail', id)


@require_POST
def choice_create(request, id):
    question = get_object_or_404(Question, id=id)
    choice_form = ChoiceForm(request.POST)
    if choice_form.is_valid():
        choice = choice_form.save(commit=False)
        choice.question = question
        choice_form.save()

    return redirect("questions:detail", id)


@require_POST
def choice_delete(request, question_id, choice_id):
    choice = get_object_or_404(Choice, id=choice_id)
    choice.delete()
    return redirect('questions:detail', question_id)

accounts/templates/accounts/form.html
{% extends 'questions/base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action="" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="가입" class="btn btn-primary">
</form>
{% endblock %}

questions/templates/questions/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% bootstrap_css %}
  <title>Document</title>
</head>

<body>
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'questions:index' %}">홈</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'questions:create' %}">글쓰기</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link disabled">{{user.username}}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'accounts:logout' %}">로그아웃</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'accounts:signup' %}">회원가입</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'accounts:login' %}">로그인</a>
    </li>
    {% endif %}
  </ul>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>

</html>

questions/templates/questions/detail.html
{% extends 'questions/base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="jumbotron">
  <h1 class="display-4 text-center">{{question.title}}</h1>
  <p class="lead text-center">{{question.choice_1}} vs {{question.choice_2}}</p>

  <div class="progress my-3">
    <div class="progress-bar" role="progressbar" style="width: {{percent_1}}%" aria-valuenow="15" aria-valuemin="0"
      aria-valuemax="100">{{percent_1|floatformat}}%</div>
    <div class="progress-bar bg-danger" role="progressbar" style="width: {{percent_2}}%" aria-valuenow="30"
      aria-valuemin="0" aria-valuemax="100">{{percent_2|floatformat}}%</div>
  </div>

  <a href="{% url 'questions:update' question.id %}" class="btn btn-warning">수정</a>
  <form action="{% url 'questions:delete' question.id %}" method="post" class="d-inline">
    {% csrf_token %}
    <input type="submit" value="삭제" class="btn btn-danger">
  </form>
  <hr class="my-4">

  <a href="" class="btn btn-primary">왼쪽</a>
  <a href="" class="btn btn-danger">오른쪽</a>
  <form action="{% url 'questions:choice_create' question.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form choice_form %}
    <input type="submit" value="고르기" class="btn btn-light">
  </form>

  {% for choice in question.choice_set.all %}


  {% if choice.pick == 1 %}
  <div class="alert alert-primary" role="alert">
    {% else %}
    <div class="alert alert-danger" role="alert">
      {% endif %}
      {{choice.comment}}
      <form action="{% url 'questions:choice_delete' question.id choice.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn btn-dark">
      </form>
    </div>
    {% endfor %}
  </div>
  {% endblock %}

questions/templates/questions/form.html
{% extends 'questions/base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action="" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit">
</form>
{% endblock %}

questions/templates/questions/index.html
{% extends 'questions/base.html' %}
{% block body %}
<h1>index</h1>
{% for question in questions %}
<div class="card">
  <div class="card-header">
    {{question.title}}
  </div>
  <div class="card-body">
    <p class="card-text text-center">{{question.choice_1}}</p>
    <p class="card-text text-center">{{question.choice_2}}</p>
    <a href="{% url 'questions:detail' question.id %}" class="btn btn-primary">투표하러가기</a>
  </div>
</div>
{% endfor %}
{% endblock %}